[build]
  bin="./tmp/main"
  cmd = "templ generate && go build -o ./tmp/main cmd/main.go"
  delay=0
  exclude_regex = [".*_templ.go"]
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]


[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true