version: '3.8'
services:  
  shortr-app:    
    build:      
      context: .      
      dockerfile: Dockerfile    
    ports:      
      - "8080:8080"    
    restart: unless-stopped
    command: ["/shortr", "--url", "app.4rkal.com"]
